app/app/convert/routes.py
import logging
import os
import shutil
from datetime import datetime

from flask import Blueprint
from flask import redirect, request

from app import database, util
from app import file_system
from app import url
from app.convert import interface, process, render, spider, arxiv
from app.database import ArticleStatusQuery, ArticleStatus, ArticleErrorInfo
from app.nocache import nocache

convert_blueprint = Blueprint('convert_blueprint', __name__)


@convert_blueprint.route('/')
def index_page():
    # TODO: move offline processor somewhere else
    # Uncomment the following line to obtain the latest fields dictionary
    # fields = arxiv.arxiv_index()
    fields = sorted(util.homepage_fields(), key=lambda item: item['field'])
    return render.render_template('home.html', fields=fields)


@convert_blueprint.route('/list/<category_name>/')
@nocache
def listings(category_name):
    try:
        article_list = database.ListingCacher().get_article_list(category_name)
        category_display_name = util.field_lookup_table.get(category_name)
        title_text = category_display_name + util.TITLE_SUFFIX
        return render.render_template('listing.html', articles=article_list, category_name=category_name,
                                      category_display_name=category_display_name, title_text=title_text)
    except Exception as e:
        if util.PRODUCTION:
            return render.render_error_message(e)
        else:
            raise e


@convert_blueprint.route('/search_result/')
def search_result():
    """Access from the homepage html"""
    query = request.args.get("query")

    # Direct arxiv id
    matched = url.ARXIV_ID_RE.match(query)
    if matched:
        id = url.article_name_convention(matched.group(), 'url')
        return redirect('/article/%s/' % id)

    # url
    matched = url.ARXIV_URL_RE.search(query)  # search because url can be prepended with http(s)://
    if matched:
        id = url.article_name_convention(matched.group(1), 'url')
        return redirect('/article/%s/' % id)

    # TOdo: try catch
    article_list = arxiv.query_page(search_query=query)
    return render.render_template('search.html', articles=article_list, title_text=query)


@convert_blueprint.route('/article/<article_name>/<path:filename>')
@convert_blueprint.route('/test/<article_name>/<path:filename>')
@nocache
def resources(article_name, filename):
    return file_system.send_resource(article_name, filename)


@convert_blueprint.route('/test/<article_name>/c')
@nocache
def test_article_convert(article_name):
    """
    :param article_name:
    :return:
    """
    if not util.PRODUCTION:
        article_request = interface.ArticleFetchRequest(article_name=article_name,
                                                        test_mode=True,
                                                        reset_local=True)
        return article_main(article_request)
    raise FileNotFoundError("Testing environment unavailable.")


@convert_blueprint.route('/test/<article_name>/')
@nocache
def test_article(article_name):
    '''
    For local testing, target article has to present
    :param article_name:
    :return:
    '''
    if not util.PRODUCTION:
        article_request = interface.ArticleFetchRequest(article_name=article_name,
                                                        test_mode=True,
                                                        preview_mode=True,
                                                        reset_local=False,
                                                        use_database=False)
        return article_main(article_request)
        # return render.render_pandoc(article_name)
    raise FileNotFoundError("Testing environment unavailable.")


@convert_blueprint.route('/article/<article_name>/')
@nocache
def article_v2(article_name):
    article_request = interface.ArticleFetchRequest(article_name=article_name)
    return article_main(article_request)


@convert_blueprint.route('/ajax_download')
@nocache
def article_download():
    """
    Ajax call from loading page, invoked in two-session loading. Process article and populate the status to ArticleStatusQuery,
    :return: empty json
    """
    article_name = str(request.args.get('article', '0'))
    is_preview = str(request.args.get('preview', '0')) == 'True'
    try:
        download_and_process_article(article_name, is_preview)
    except interface.NotInLatexError as e:
        ArticleStatusQuery(article_name).set(ArticleStatus.FAILED, ArticleErrorInfo.NOTINLATEX)
    except interface.RenderError as e:
        ArticleStatusQuery(article_name).set(ArticleStatus.FAILED, ArticleErrorInfo.RENDER)
    except interface.ArticleNotFoundError as e:
        ArticleStatusQuery(article_name).set(ArticleStatus.FAILED, ArticleErrorInfo.NOTFOUND)
    except interface.ArticleConnectionError as e:
        ArticleStatusQuery(article_name).set(ArticleStatus.FAILED, ArticleErrorInfo.CONNECTION)
    except:
        ArticleStatusQuery(article_name).set(ArticleStatus.FAILED)
    return {}


def download_and_process_article(article_name, is_preview=False):
    """
    Helper function, raises Error if process is not successful
    :param is_preview: if True, return after tex files are processed. Otherwise spawning
    :param article_name:
    :return: Nothing
    """
    spider.download_source(article_name)
    article_request = interface.ArticleFetchRequest(article_name=article_name, preview_mode=is_preview)
    process.process_v2(article_request)


@convert_blueprint.route('/helper/post_process/<article_name>')
def post_process(article_name):
    """Indirectly invoked by process.py"""
    try:
        process.post_process(article_name)
        return {}
    except FileNotFoundError:  # Files disappear in PRODUCTION
        return redirect('/article/%s/r' % article_name)


@convert_blueprint.route('/article/<article_name>/status')
def article_status(article_name):
    return ArticleStatusQuery(article_name).get()


@convert_blueprint.route('/article/<article_name>/r')
def article_redownload_v2(article_name):
    request = interface.ArticleFetchRequest(article_name=article_name, force_refresh=True)
    return article_main(request)


@convert_blueprint.route('/article/<article_name>/c')
def article_reconvert_v2(article_name):
    request = interface.ArticleFetchRequest(article_name=article_name, reset_local=True)
    return article_main(request)


def check_article_status_and_load_or_show(request: interface.ArticleFetchRequest):
    """
    Check article status from ArticleStatusQuery (prerequisite: using database),
    - If never downloaded: invoking loading page
    - If text is ready, show article (show in preview mode if images are not ready),
    - Fallback to pdf if NOTINLATEX or RENDER error but pdf exists
    - raise error otherwise
    :param request:
    :return: rendered page
    """
    article_name = request.article_name
    response = ArticleStatusQuery(article_name).get()
    if response['status'] in (ArticleStatus.UNKNOWN.name, ArticleStatus.DOWNLOADING.name):
        logging.info("%s does not exist, invoke loading page." % article_name)
        content = {"article_name": article_name, "is_preview": True}
        return render.render_template('loading.html', **content)
    elif response['status'] in (ArticleStatus.SUCCESS.name, ArticleStatus.RENDERING.name):
        request.preview_mode = response['status'] == ArticleStatus.RENDERING.name
        if response['expire_at'] < datetime.strptime(util.FIRST_SUPPORTED_META_VERSION, '%Y%m%d%H%M%S'):
            raise interface.CacheExpiredError()
        return show_article(request)
    elif response['status'] == ArticleStatus.FAILED.name:
        if response['info'] == ArticleErrorInfo.NOTINLATEX.name:
            request.process_pdf = True
            return article_main(request)
        elif response['info'] == ArticleErrorInfo.RENDER.name:
            request.process_pdf = True
            return article_main(request)
        elif response['info'] == ArticleErrorInfo.CONNECTION.name:
            raise interface.ArticleConnectionError()
        else:
            raise interface.ArticleNotFoundError('https://arxiv.org/pdf/%s.pdf' % article_name)


def show_article_in_one_session(request: interface.ArticleFetchRequest):
    if not file_system.access(request.article_name):
        download_and_process_article(request.article_name)
    # check if meta is expired
    interface.ArticleMeta.read(request.article_name)
    return render.render_pandoc_v2(request.article_name, False)


def show_article(request: interface.ArticleFetchRequest):
    if not file_system.access(request.article_name):
        request.force_refresh = True
        return article_main(request)
    # check if meta is expired
    interface.ArticleMeta.read(request.article_name)
    return render.render_pandoc_v2(request.article_name, request.preview_mode)


def reset_local_files(request: interface.ArticleFetchRequest):
    article_name = request.article_name
    file_system.access(request.article_name)  # Download necessary bak files
    util.remove_files([article_name + '.md',
                       article_name + '.orig.md',
                       article_name + '.html',
                       util.GENERATED_BIB_FILE_NAME], util.get_path(article_name))
    image_folder = os.path.join(util.get_path(article_name), util.LATEX_GENERATED_IMAGE_FOLDER)
    if os.path.exists(image_folder):
        shutil.rmtree(image_folder)
    if request.test_mode:
        spider.generate_mock_meta(request.article_name)
    meta = interface.ArticleMeta.read(article_name)
    util.recover_bak_files(meta.tex_files, meta.article_folder)
    if util.GENERATED_BIB_FILE_NAME in meta.bib_files:
        logging.info("Removing generated bib file.")
        meta.bib_files.remove(util.GENERATED_BIB_FILE_NAME)
    meta.latex_image_requests = ()
    meta.store()


def article_main(request: interface.ArticleFetchRequest):
    try:

app/app/user/routes.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user, login_required

from app import util
from app.user.favorites import format_article_display
from app.user.forms import LoginForm, RenameCollectionForm
from app.db_model import User, Article

user_blueprint = Blueprint('user_blueprint', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('convert_blueprint.index_page'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.find_one(email=form.email.data)
        if user is None or not user.check_password(form.password.data):
            flash('Invalid email or password')
            return redirect(url_for('user_blueprint.login'))
        login_user(user, remember=form.remember_me.data)
        flash('Welcome, {}.'.format(current_user['username']))
        return redirect(url_for('convert_blueprint.index_page'))
    return render_template('login.html', title='Sign In', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('convert_blueprint.index_page'))


# Collection management
@user_blueprint.route('/dashboard')
@login_required
def dashboard():
    form = RenameCollectionForm()
    collections = current_user.get_all_collections()  # ensures at least one collection for current user
    display_collections = {}
    for collection in collections:
        articles = []
        for pointer in collection['articles']:
            article = Article.get_from_id(pointer['id'])
            article_display = format_article_display(article, pointer['time_added'])
            articles.append(article_display)
        display_name = "Read Later" if collection['is_default'] else collection['name']
        if len(articles):
            display_name += " (%s)" % len(articles)
        display_collections[collection.get_string_id()] = {'name': display_name,
                                                           'is_default': collection['is_default'],
                                                           'articles': articles}
    return render_template('dashboard.html', title_text="Dashboard" + util.TITLE_SUFFIX,
                           collections=display_collections, form=form)


@user_blueprint.route('/favorites/add/<article_name>')
@login_required
def add_article_to_default_collection(article_name):
    article = Article.find_one(article_name=article_name)
    if not article:
        raise FileNotFoundError("Missing article in database")
    collection = current_user.get_default_collection()
    if collection.add_article(article):
        flash('Added {} to Read Later.'.format(article_name))
    else:
        flash('{} already in Read Later.'.format(article_name))
    return redirect(url_for('convert_blueprint.article_v2', article_name=article_name))


@user_blueprint.route('/favorites/remove/<article_name>/<collection_id>')
@login_required
def remove_from_collection(article_name, collection_id):
    article = Article.find_one(article_name=article_name)
    if not article:
        raise FileNotFoundError("Missing article in database")
    collection = current_user.get_collection(collection_id)
    if not collection:
        flash('Cannot find collection')
    if not collection.remove_article(article):
        flash('Cannot find {} in collection'.format(article_name))
    return redirect(url_for('user_blueprint.dashboard'))


@user_blueprint.route('/favorites/move/<article_name>/<from_id>/<to_id>')
@login_required
def move_from_collection(article_name, from_id, to_id):
    article = Article.find_one(article_name=article_name)
    if not article:
        raise FileNotFoundError("Missing article in database")
    if from_id != to_id:
        collection_from = current_user.get_collection(from_id)
        collection_to = current_user.get_collection(to_id)
        if not collection_from or not collection_to:
            flash('Cannot find collection')
        if not collection_from.remove_article(article):
            flash('Cannot find {} in collection'.format(article_name))
        if not collection_to.add_article(article):
            flash('Error in adding article')
    return redirect(url_for('user_blueprint.dashboard'))


# method: post
# def remove_from_collection()

@user_blueprint.route('/favorites/create_collection')
@login_required
def create_collection():
    current_user.create_collection("New collection")
    return redirect(url_for('user_blueprint.dashboard'))


@user_blueprint.route('/favorites/delete_collection/<collection_id>')
@login_required
def delete_collection(collection_id):
    current_user.remove_collection(collection_id)
    return redirect(url_for('user_blueprint.dashboard'))


@user_blueprint.route('/favorites/rename_collection', methods=['POST'])
@login_required
def rename_collection():
    form = RenameCollectionForm()
    if form.validate_on_submit():
        current_user.rename_collection(string_id=form.current_collection_id.data,
                                       new_name=form.name.data)
    return redirect(url_for('user_blueprint.dashboard'))

app/app/templates/article.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<meta id="article-metadata" data-articlename="{{article_name}}" data-preview="{{is_preview}}">
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/css/blog.css') }}">
{% endblock %}
{% block title %}{{title_text}}{% endblock %}
{% block content %}
<div class="container">
  <div class="blog-header">
    <h3 class="blog-title">{{title}}</h3>
    <p class="blog-post-meta">{{author}}</p>
    <p class="blog-post-date">{{update_time}}</p>
    <hr>
  </div>
  <div class="row">
    <div class="col-md-8 blog-main">
      <div class="blog-post">
        {{abstract}}
        {{toc}}
        {{body}}
      </div>
      <!--            <nav>-->
      <!--                <ul class="pager">-->
      <!--                    <li><a href="#">Previous</a></li>-->
      <!--                    <li><a href="#">Next</a></li>-->
      <!--                </ul>-->
      <!--            </nav>-->
    </div><!-- /.blog-main -->
    <div class="col-md-4 blog-sidebar order-md-last order-first sans">
      <div class="sidebar-module sidebar-module-inset">
        <p><h4>Subjects</h4></p>
        <p><b>{{subject.primary_subject}}</b></p>
        {%for item in subject.secondary_subject%}
        <p>{{item}}</p>
        {%endfor%}
        <p><h4>Updated on Academus</h4></p>
        <div>{{academus_time}} UTC</div>
        <p><h4>
        <a href="https://arxiv.org/pdf/{{article_name}}.pdf" target="_blank" title="View PDF"><i
            class="fa fa-file-pdf-o"
            aria-hidden="true"></i></a>
        {% if not current_user.is_anonymous %}
        <a href="{{ url_for('user_blueprint.add_article_to_default_collection', article_name=article_name) }}"
           title="Add to collection"><i class="fa fa-plus" aria-hidden="true"></i></a>
        {% endif %}
      </h4>        </p>
      </div>
    </div><!-- /.blog-sidebar -->

  </div><!-- /.row -->
</div><!-- /.container -->
{% endblock %}
{% block script %}
<!--   Modal -->
<div id="modal-container" class="modal-class">
  <div class="modal-content">
    <span class="modal-close" onclick="closeModal()">&times;</span>
    <div class="modal-image"></div>
  </div>
</div>
<script>
      function addScroll() {
      $('table').parent().addClass('table-scroll');
      }
      addScroll();
</script>
<!--modal function-->
<script>
var modal = document.getElementById("modal-container");
var modalimage = document.querySelector(".modal-image");

function modal_figure_popup(input){
  event.preventDefault();
  modalimage.innerHTML='';
  var id = input.href.match(/#.*/)[0].replace('#','');
  var content = document.getElementById(id).closest("figure");
  console.log(content);
  modalimage.insertAdjacentHTML('afterbegin',content.innerHTML);
  modal.classList.add("fade-in");
  document.querySelector('html').classList.add("body-scroll");
}

function modal_equation_popup(input){
  event.preventDefault();
  modalimage.innerHTML='';
  var id = input.href.match(/#.*/)[0].replace('#','');
  var content = document.getElementById(id).closest("span.eqnos");
  console.log(content);
  modalimage.insertAdjacentHTML('afterbegin',content.innerHTML);
  modal.classList.add("fade-in");
  document.querySelector('html').classList.add("body-scroll");
}

function closeModal(){
  modal.classList.remove("fade-in");
  document.querySelector('html').classList.remove("body-scroll");
}

</script>
<!--modal function ends-->
<!--Async loading images-->
<script>
$(function () {
    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
    async function refresh() {
        var waiting = true;
        var retry = 0;
        while (waiting && retry < 180) {
            $.ajax({
              url: '/article/' + $('#article-metadata').data().articlename + '/status',
              type: 'get',
              dataType: 'JSON',
              success: function(response) {
                if (response.status == 'SUCCESS') {
                    waiting = false;
                    console.log("Background image ready.");
                    $.each(document.images, function(){
                        var this_image = this;
                        var asrc = $(this_image).attr('asrc') || '' ;
                        if( asrc.length > 0 ){
                            this_image.src = asrc;
                        }
                    });
                }
              },
              error: function(error) {
                console.log(error);
              }
            });
            retry += 1;
            await sleep(2000);
        }
    }
    if ($('#article-metadata').data().preview == "True"){
        refresh();
    }
})

</script>
{% endblock %}

app/app/templates/base.html
<!doctype html>
<html lang="en">
<head>
  {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{{ url_for('static',filename='assets/icon.png') }}">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-162139659-1"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-162139659-1');




  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/fonts/Serif/cmun-serif.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/css/sans_serif.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/css/default.css') }}">
  <title>{% block title %}{% endblock %}</title>
  {% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-sm navbar-dark blog-masthead sans">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('convert_blueprint.index_page')}}">
      <img src="{{ url_for('static',filename='assets/logo.png') }}" height="30" width="120">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if not current_user.is_anonymous %}
        <a class="nav-link active" href="{{ url_for('user_blueprint.dashboard')}}"> Dashboard</a>
        {% endif %}
      </div>
      <div class="navbar-nav ms-auto">
        {% if current_user.is_anonymous %}
        <a class="nav-link" href="#">Sign Up
          <span class="top-0 start-100 badge rounded-pill bg-secondary">
            Coming soon
          </span>
        </a>
        <a class="nav-link active" href="{{ url_for('user_blueprint.login')}}"> Login</a>
        {% else %}
        <a class="nav-link active">{{current_user['username']}}</a>
        <a class="nav-link active" href="{{ url_for('user_blueprint.logout')}}"> Logout</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
  {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

{% block content %}{% endblock %}

<footer class="blog-footer sans">
  {% block footer %}
  <p>Copyright 2021 academ.us <a href="https://twitter.com/academus_main">Contact Us <i class="fa fa-twitter"></i></a>
  </p>
  {% endblock %}
</footer>
{% block script %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

app/app/templates/dashboard.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
{% endblock %}
{% block title %}{{title_text}}{% endblock %}
{% block content %}
<div class="container">
  <div class="blog-header">
    <h1 class="blog-title sans">Dashboard</h1>
  </div>
  <hr>
  <div class="row">
    <div class="col-sm-3 sans">
      <div id="collections" data-landing-collection-id="{{landing_collection_id}}">
        <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
            <form action="{{ url_for('user_blueprint.rename_collection') }}" method="post" novalidate id="rename-form" style="display: none">
            {{ form.hidden_tag() }}
              <div class="input-group">
                {{ form.name(size=256, class="form-control") }}
                {{ form.current_collection_id(class="form-control") }}
                <button type=submit class="btn btn-primary" id="rename-submit-btn"><i class="fa fa-check" aria-hidden="true"></i></button>
              </div>
            </form>
          {% for id, collection in collections.items() %}
          <div class="collection-container">
          <div class="btn-group justify-content-between w-100" role="group" aria-label="Button group with dropdown">
            <button class="nav-link collection-tab w-100" type="button" role="tab" aria-selected="true" data-collection-id="{{id}}" data-collection-is-default="{{collection.is_default}}">{{collection.name}}</button>
              {% if collection.is_default %}
              <div class="dropdown">
                <button class="btn" type="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item rename-submenu disabled" href="#">Rename</a></li>
                </ul>
              </div>
              {% else %}
              <div class="dropdown">
                <button class="btn" type="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item rename-submenu" data-collection-id="{{id}}" href="#">Rename</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('user_blueprint.delete_collection', collection_id=id)}}">Delete Collection</a></li>
                </ul>
              </div>
              {% endif %}
          </div>
          </div>
          {% if collection.is_default %}
          <hr>
          {% endif %}
          {% endfor %}
        </div>
      </div>
      <button class="btn" type="button" ><a href="{{ url_for('user_blueprint.create_collection') }}" title="Add collection"><i class="fa fa-plus" aria-hidden="true"></i></a></button>
    </div> <!--col-->
    <div class="col-sm-9 sans">
      {% for collection_id, collection in collections.items() %}
      <div class="collection-article-list" id="{{collection_id}}">
        {% for article in collection.articles %}
        <div class="list-group">
          <div class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
              <a href="{{article['url']}}" target="_blank"><h5 class="mb-1">{{article['title']}}</h5></a>
              <div class="time-ago"><small class="text-muted">{{article['time_added']}}</small></div>
            </div>
            <p class="mb-1">{{article['author_str']}}</p>
            <small class="text-muted">{{article['article_name']}}</small>
            <div class="dropdown">
              <button class="btn" type="button"
                      data-bs-toggle="dropdown" aria-expanded="false" style="float: right;">
                <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ url_for('user_blueprint.remove_from_collection', article_name=article['article_name'], collection_id=collection_id) }}">Remove from collection</a></li>
                <li>
                  <a class="dropdown-item move-to-collection-item d-flex justify-content-between">Move to... <i class="fa fa-caret-right menu-expand-arrow" aria-hidden="true"></i></a>
                    <ul class="dropdown-menu dropdown-submenu-left">
                    {% for other_id, other_collection in collections.items() %}
                      <li><a class="dropdown-item" href="{{ url_for('user_blueprint.move_from_collection', article_name=article['article_name'], from_id=collection_id, to_id=other_id) }}" >{{other_collection.name}}</a></li>
                    {% endfor %}
                    </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endfor %}
    </div> <!--col-->
  </div> <!--row-->
  <hr>
</div><!-- /.container -->

{% endblock %} <!--content-->

{% block script %}
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
<script>
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
};

</script>
<script type="text/javascript" src="{{ url_for('static',filename='styles/js/dashboard.js') }}"></script>
{% endblock %}

app/app/templates/home.html
{% extends "base.html" %}
{% block title %}Academus - Next generation scientific article reader{% endblock %}
{% block content %}
<!--Search background-->
<div class="home-page-outer">
  <div class="home-page-inner">
    <div>
      <img class="home-page-logo" src="{{ url_for('static',filename='assets/logo_color.png') }}">
    </div>
    <!--Form and button-->
    <form action="{{ url_for('convert_blueprint.search_result')}}" class="" method="get">
      <div class="input-group input-group-lg">
        <input autofocus="" class="form-control" name="query" placeholder="Search or type arXiv id" type="text"
               value="">
        <button class="btn btn-primary" type="submit">Go</button>
      </div>
    </form>
    <div
        data-tooltip="You can also type article id (e.g. 2001.00001) or paste arXiv abstract page URL/pdf link in the search box.">
      &#9432;
    </div>
    <!--Form and button ends-->
    <div class="home-page-slogan">
      Interactive. Intelligent.<br>The next generation scientific article reader.
    </div>
  </div>
</div><!--Search background-->
<!--New articles list-->
<div class="home-page-bottom">
  <div class="container">
    <div class="row">
      {% for field in fields %}
      <div class="col-sm-12 col-lg-6">
        <a href="{{url_for('convert_blueprint.listings', category_name = field.abbreviation)}}"
           target="_blank">{{field.field}}</a>
        <hr>
      </div>
      {% endfor %}
    </div>
  </div>
</div><!--New articles list-->
{% endblock %}